name: Build CamillaDSP with JACK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libjack-jackd2-dev
    - name: Build CamillaDSP
      run: cargo build --release --features jack
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: camilladsp
        path: target/release/camilladsp
