name: Build CamillaDSP w/ JACK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libjack-jackd2-dev pkg-config libasound2-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build CamillaDSP (release with jack)
        run: |
          RUSTFLAGS="-A clippy::uninlined_format_args" cargo build --release --features jack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: camilladsp-jack-linuxmint24
          path: target/release/camilladsp
