name: Build CamillaDSP with JACK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjack-jackd2-dev pkg-config libasound2-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build CamillaDSP (release with jack feature)
        run: cargo build --release --features jack-backend

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: camilladsp-release
          path: target/release/camilladsp
