name: Build CamillaDSP with JACK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libjack-jackd2-dev libasound2-dev pkg-config

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build CamillaDSP with JACK
      run: cargo build --release --features jack-backend

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: camilladsp-release
        path: target/release/camilladsp
