name: Build CamillaDSP Full Feature

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjack-jackd2-dev \
            pkg-config \
            libasound2-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            libdbus-1-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build CamillaDSP (release with full features)
        run: cargo build --release --features "jack-backend ncurses matrix channel-routing"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: camilladsp-full-feature
          path: target/release/camilladsp
